export const tricks: any[] = [
    {label: 'Center elements', stackblitz: 'https://stackblitz.com/edit/center-element?file=index.html&hideNavigation=1&theme=light'},
    {label: 'Flex The Box', stackblitz: 'https://stackblitz.com/edit/flex-the-box?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/flexbox'},
    {label: 'Even and Odd', stackblitz: 'https://stackblitz.com/edit/even-oddy?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/mdn-css_selectors_nth-of-type'},
    {label: 'box-sizing', stackblitz: 'https://stackblitz.com/edit/border-box-sizing?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/css3-boxsizing'},
    {label: 'Outline text', stackblitz: 'https://stackblitz.com/edit/outline-text?file=index.html', caniuse: 'https://caniuse.com/text-stroke'},
    {label: 'Primitive shapes without SVG', stackblitz: 'https://stackblitz.com/edit/primitive-shapes?file=index.html&hideNavigation=1&theme=light'},
    {label: 'CSS image processing', stackblitz: 'https://stackblitz.com/edit/image-processing-bean?file=styles.css&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/css-filters'},
    {label: 'Scaling of grouped content', stackblitz: 'https://stackblitz.com/edit/group-scaling?file=styles.css&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/transforms2d'},
    {label: 'State transitions', stackblitz: 'https://stackblitz.com/edit/state-transitions?file=src/app/app.component.css&theme=light', caniuse:'https://caniuse.com/mdn-css_properties_transition'},
    {label: 'Why :not(!?)', stackblitz: 'https://stackblitz.com/edit/not-css-fn?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/css-not-sel-list'},
    {label: '@supports', stackblitz: 'https://stackblitz.com/edit/css-supports?file=styles.css&hideNavigation=1', caniuse: 'https://caniuse.com/css-supports-api'},
    {label: 'Ellipsis...', stackblitz: 'https://stackblitz.com/edit/ellipsis-css?file=styles.css&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/css-line-clamp'},
    {label: ':target', stackblitz: 'https://stackblitz.com/edit/target-css?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/mdn-css_selectors_target'},
    {label: 'Embed your stuff!!', stackblitz: 'https://stackblitz.com/edit/embedding-data?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/datauri'},
    //{label: 'Forms and Labels'},
    {label: 'Media Queries', stackblitz: 'https://stackblitz.com/edit/mediaqueries?file=styles.css', caniuse: 'https://caniuse.com/css-mediaqueries'},
    //{label: 'Units (em, rem, ch, px...)'},
    {label: 'min(), max(), clamp()', stackblitz: 'https://stackblitz.com/edit/minmaxclamp?file=styles.css&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/css-math-functions'},
    {label: 'calc()', stackblitz: 'https://stackblitz.com/edit/calc-it?file=index.html&hideNavigation=1&theme=light', caniuse: 'https://caniuse.com/calc'},
    {label: 'underlined? overrated!', stackblitz: 'https://stackblitz.com/edit/underlined?file=index.html&hideNavigation=1&theme=light'},
    {label: 'Viewport units', stackblitz: 'https://stackblitz.com/edit/viewport-dependent-units?file=styles.css&hideNavigation=1', caniuse: 'https://caniuse.com/viewport-units'},
];
